### ISSUE TITLE
Filter does not seem to work

### ISSUE THREAD

**Issue by freder** [awoojs/core#8]
with

```js
const mdFilesFilter = (file, options, files) => {
	return file.path.endsWith('.md');
};

// [...]

site.use(matter, { filter: mdFilesFilter });
```

`.DS_Store` still makes it through, even though the filter function return `false`.

**Comment by zipang** [comment]
Hi @freder 
As stated in the plugin's README : the `filter` param can be used to select files on which the transformation is applied, leaving the others _unchanged_ (so they are still inside the `files` array).
So i guess that if you want to get rid of every non-markdown files before passing them to `matter`, you should first apply an [Array filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) like so : 

```
function excludeJunkFiles() {
  return files => files.filter(file => file.extname === '.md');
}
site.use(excludeJunkFiles);
// now files should only contains markdown files
site.use(matter);

```

**Comment by freder** [comment]
ah, I see. + yes, that's what I ended up doing. — thx!
